"""
Django settings for stockcontrol project - Cloud Run version.

Generated by 'django-admin startproject' using Django 6.0.3.
Updated for Cloud Run deployment.
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env()

# Read the .env file in your local environment
# This line is safe to keep as it only runs if the file exists.
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-your-secret-key-here-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)  # Changed to False for Cloud Run

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])  # Allow all hosts for Cloud Run


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock',  # Your stock app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ADDED: For serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stockcontrol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockcontrol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Check if we're running on Google Cloud (using Unix socket)
if os.environ.get('USE_CLOUD_SQL_SOCKET', 'false').lower() == 'true':
    # For Cloud Run/App Engine: Use the Unix socket provided by Google Cloud
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': f"/cloudsql/{env('INSTANCE_CONNECTION_NAME')}",
            'PORT': '5432',
        }
    }
else:
    # For local development: Use a standard TCP connection
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME', default='your_local_db_name'),
            'USER': env('DB_USER', default='your_local_db_user'),
            'PASSWORD': env('DB_PASSWORD', default='your_local_password'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES (CSS, JavaScript, Images) - FIXED
# ============================================================

STATIC_URL = '/static/'  # CHANGED: Added leading slash

# IMPORTANT: This is the directory where collectstatic will put all static files
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ADDED: This was missing!

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # If you have a static directory in your app
]

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# AUTHENTICATION SETTINGS
# ============================================================

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ============================================================
# EMAIL CONFIGURATION - FIXED
# ============================================================

# Option 1: For Gmail (REAL EMAIL SENDING)
# You need to use an App Password, NOT your regular password
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kiyimbahenry314@gmail.com'
EMAIL_HOST_PASSWORD = 'oetpdk6fs5utanbq62q6rwbuzxu53kf7'  # App Password
DEFAULT_FROM_EMAIL = 'kiyimbahenry314@gmail.com'

# Option 2: For Testing (PRINTS EMAIL TO CONSOLE)
# Uncomment this to test without sending real emails
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ============================================================
# CLOUD RUN SPECIFIC SETTINGS
# ============================================================

# Security settings for Cloud Run
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)

# For Cloud Run with HTTPS termination
if os.environ.get('CLOUD_RUN', '').lower() == 'true':
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Trust the Cloud Run proxy headers
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Use the host header provided by Cloud Run
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

# ============================================================
# LOGGING CONFIGURATION (Optional)
# ============================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
