# Generated by Django 6.0.3 on 2026-07-07 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_invoice_options_drug_strength_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drug',
            name='stock_drug_barcode_dee8d8_idx',
        ),
        migrations.AddField(
            model_name='drug',
            name='batch_no',
            field=models.CharField(blank=True, help_text='Batch/Lot number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('capsules', 'Capsules'), ('injection', 'Injection'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('drops', 'Drops'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('jerry', 'Jerry'), ('oil', 'Oil'), ('spray', 'Spray'), ('gel', 'Gel'), ('powder', 'Powder'), ('liquid', 'Liquid'), ('balm', 'Balm')], default='tablet', help_text='Select the dosage form', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Default 50% (1.5x cost price)', max_digits=5),
        ),
        migrations.AddField(
            model_name='drug',
            name='pack_size',
            field=models.CharField(blank=True, help_text='e.g., 10 tablets, 100ml', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['batch_no'], name='stock_drug_batch_n_ea48e7_idx'),
        ),
        migrations.RemoveField(
            model_name='drug',
            name='purchase_price',
        ),
    ]
