# Generated by Django 6.0.3 on 2026-07-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_drug_stock_drug_barcode_dee8d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.AlterField(
            model_name='drug',
            name='pack_size',
            field=models.PositiveIntegerField(default=0, help_text='Number of units per packet'),
        ),
    ]
