# Generated by Django 6.0.3 on 2026-07-08 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.TextField(blank=True)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('disease_type', models.CharField(choices=[('HIV', 'HIV/AIDS'), ('HYPERTENSION', 'Hypertension'), ('DM', 'Diabetes Mellitus'), ('NEURO', 'Neuro Care'), ('ULCERS', 'Ulcers'), ('ASTHMA', 'Asthma'), ('CANCER', 'Cancer'), ('KIDNEY', 'Kidney Disease'), ('HEART', 'Heart Disease'), ('OTHER', 'Other')], max_length=20)),
                ('other_disease', models.CharField(blank=True, help_text="Specify if disease is 'Other'", max_length=100)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, help_text='List of medications the patient is taking')),
                ('dosage', models.TextField(blank=True, help_text='Dosage information for each medication')),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg twice daily', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Morning, Evening, Daily', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 months, Ongoing', max_length=100)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_medications', to='stock.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_list', to='stock.chronicpatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('visit_type', models.CharField(choices=[('regular', 'Regular Checkup'), ('emergency', 'Emergency'), ('followup', 'Follow-up'), ('medication', 'Medication Pickup')], default='regular', max_length=50)),
                ('complaints', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=dict, help_text='Blood Pressure, Heart Rate, Temperature, etc.')),
                ('notes', models.TextField(blank=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='stock.chronicpatient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddIndex(
            model_name='chronicpatient',
            index=models.Index(fields=['patient_id'], name='stock_chron_patient_85f795_idx'),
        ),
        migrations.AddIndex(
            model_name='chronicpatient',
            index=models.Index(fields=['first_name', 'last_name'], name='stock_chron_first_n_695af1_idx'),
        ),
        migrations.AddIndex(
            model_name='chronicpatient',
            index=models.Index(fields=['disease_type'], name='stock_chron_disease_f757cd_idx'),
        ),
    ]
