# Generated by Django 6.0.3 on 2026-07-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_chronicpatient_patientmedication_patientvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_items',
            field=models.PositiveIntegerField(default=0, help_text='Total number of items on this invoice'),
        ),
    ]
