# Generated by Django 6.0.3 on 2026-07-09 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_invoice_payment_mode_invoice_total_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_refund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_created', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='stock.drug')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='stock.receipt')),
            ],
            options={
                'verbose_name_plural': 'Returned Drugs',
                'ordering': ['-returned_date'],
            },
        ),
    ]
