# Generated by Django 6.0.3 on 2026-08-27 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_create_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['brand'], name='stock_drug_brand_d83045_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['generic_name'], name='stock_drug_generic_68f05a_idx'),
        ),
    ]
