# Generated by Django 6.0.3 on 2026-09-02 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_drug_stock_drug_brand_d83045_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dosage Form',
                'verbose_name_plural': 'Dosage Forms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='cleared_by',
            field=models.ForeignKey(blank=True, help_text='User who cleared this credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cleared_date',
            field=models.DateTimeField(blank=True, help_text='When the credit was cleared', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_cleared',
            field=models.BooleanField(default=False, help_text='True if credit has been paid'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_credit',
            field=models.BooleanField(default=False, help_text='True if this is a credit sale'),
        ),
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_receipt_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('items', models.JSONField(default=list)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_sales_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_sales_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Sale',
                'verbose_name_plural': 'Credit Sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments_created', to=settings.AUTH_USER_MODEL)),
                ('credit_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stock.creditsale')),
            ],
            options={
                'verbose_name': 'Credit Payment',
                'verbose_name_plural': 'Credit Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='credit_sale',
            field=models.ForeignKey(blank=True, help_text='Reference to the credit sale if this receipt is from a credit transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='stock.creditsale'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['is_credit'], name='stock_recei_is_cred_cb3dee_idx'),
        ),
        migrations.AddField(
            model_name='dosageform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosage_forms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['credit_receipt_number'], name='stock_credi_credit__293839_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['customer_name'], name='stock_credi_custome_df2fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['status'], name='stock_credi_status_edca53_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['due_date'], name='stock_credi_due_dat_3859e2_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['created_at'], name='stock_credi_created_0aefb9_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['credit_sale'], name='stock_credi_credit__fa3cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['created_at'], name='stock_credi_created_53e529_idx'),
        ),
    ]
